Improve emit commandline tools

diff --git a/misc/emit_notification b/misc/emit_notification
--- a/misc/emit_notification
+++ b/misc/emit_notification
@@ -3,4 +3,8 @@
 filename="$1"
 destination="${2:-audio}"
 
-amqp-publish -u "amqp://${AMQP_SERVER:-localhost}" -e notify -r "${destination}" <  "${filename}"
+if [[ ! -r $filename ]]; then
+    echo "$0: File error" >&2
+else
+    amqp-publish -u "amqp://${AMQP_SERVER:-localhost}" -e notify -r "${destination}" <  "${filename}"
+fi
